// lib/rssSources.js
// Türk haber sitesi RSS kaynakları — kategori bazlı organize
// icon: favicon URL — detail sayfasında kaynak logosu olarak kullanılır

const SOZCU_FAVICON = "https://www.sozcu.com.tr/static/web/assets/favicon.webp";
const TECHNOPAT_ICON =
  "https://www.technopat.net/wp-content/uploads/2025/10/192x192.png";

export const RSS_SOURCES = [
  // ── GÜNDEM / POLİTİKA ────────────────────────────────────────────────────
  {
    id: "trt_haber",
    name: "TRT Haber",
    url: "https://www.trthaber.com/sondakika.rss",
    icon: "https://www.trthaber.com/favicon.ico",
    categories: ["politics"],
    lang: "tr",
    priority: 1,
  }, 
  {
    id: "onedio_gundem",
    name: "Onedio Gündem",
    url: "https://onedio.com/Publisher/publisher-gundem.rss",
    icon: "https://onedio.com/favicon.ico",
    categories: ["politics"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "onedio_teknoloji",
    name: "Onedio Teknoloji",
    url: "https://onedio.com/Publisher/publisher-teknoloji.rss",
    icon: "https://onedio.com/favicon.ico",
    categories: ["technology"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "onedio_ekonomi",
    name: "Onedio Ekonomi",
    url: "https://onedio.com/Publisher/publisher-ekonomi.rss",
    icon: "https://onedio.com/favicon.ico",
    categories: ["business"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "hurriyet",
    name: "Hürriyet",
    url: "https://www.hurriyet.com.tr/rss/anasayfa",
    icon: "https://www.hurriyet.com.tr/favicon.ico",
    categories: ["politics", "world", "business"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "sabah",
    name: "Sabah",
    url: "https://www.sabah.com.tr/rss/anasayfa.xml",
    icon: "https://www.sabah.com.tr/favicon.ico",
    categories: ["politics", "world", "business"],
    lang: "tr",
    priority: 3,
  },
  {
    id: "milliyet",
    name: "Milliyet",
    url: "https://www.milliyet.com.tr/rss/rssNew/gundemRss.xml",
    icon: "https://www.milliyet.com.tr/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "sozcu",
    name: "Sözcü",
    url: "https://www.sozcu.com.tr/feeds-rss-category-gundem",
    icon: SOZCU_FAVICON,
    categories: ["politics", "world"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "cumhuriyet",
    name: "Cumhuriyet",
    url: "https://www.cumhuriyet.com.tr/rss/son_dakika.xml",
    icon: "https://www.cumhuriyet.com.tr/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "aa_gundem",
    name: "Anadolu Ajansı",
    url: "https://www.aa.com.tr/tr/rss/default?cat=gundem",
    icon: "https://www.aa.com.tr/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "bbc_turkce",
    name: "BBC Türkçe",
    url: "https://feeds.bbci.co.uk/turkce/rss.xml",
    icon: "https://www.bbc.co.uk/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "dw_turkce",
    name: "DW Türkçe",
    url: "https://rss.dw.com/rdf/rss-tur-all",
    icon: "https://www.dw.com/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "haberturk",
    name: "Habertürk",
    url: "https://www.haberturk.com/rss",
    icon: "https://www.haberturk.com/favicon.ico",
    categories: ["politics", "world", "business"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "ntv",
    name: "NTV",
    url: "https://www.ntv.com.tr/son-dakika.rss",
    icon: "https://www.ntv.com.tr/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "cnnturk",
    name: "CNN Türk",
    url: "https://www.cnnturk.com/feed/rss/all/news",
    icon: "https://www.cnnturk.com/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "t24",
    name: "T24",
    url: "https://t24.com.tr/rss",
    icon: "https://t24.com.tr/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "teyit",
    name: "Teyit",
    url: "https://teyit.org/feed?lang=tr",
    icon: "https://teyit.org/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "gazeteduvar",
    name: "Gazete Duvar",
    url: "https://www.gazeteduvar.com.tr/export/rss",
    icon: "https://www.gazeteduvar.com.tr/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "journo",
    name: "Journo",
    url: "https://journo.com.tr/feed",
    icon: "https://journo.com.tr/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "independent_tr",
    name: "Independent Türkçe",
    url: "https://www.indyturk.com/rss.xml",
    icon: "https://www.indyturk.com/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "birgun",
    name: "BirGün",
    url: "https://www.birgun.net/rss/son-dakika.rss",
    icon: "https://www.birgun.net/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 3,
  },
  {
    id: "diken",
    name: "Diken",
    url: "https://www.diken.com.tr/feed/",
    icon: "https://www.diken.com.tr/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 3,
  },
  {
    id: "bianet",
    name: "Bianet",
    url: "https://bianet.org/bianet.rss",
    icon: "https://bianet.org/favicon.ico",
    categories: ["politics", "world"],
    lang: "tr",
    priority: 3,
  },
  {
    id: "odatv",
    name: "OdaTV",
    url: "https://www.odatv.com/rss.xml",
    icon: "https://www.odatv.com/favicon.ico",
    categories: ["politics"],
    lang: "tr",
    priority: 3,
  },

  // ── EKONOMİ ──────────────────────────────────────────────────────────────
  {
    id: "dunya",
    name: "Dünya Gazetesi",
    url: "https://www.dunya.com/rss",
    icon: "https://www.dunya.com/favicon.ico",
    categories: ["business"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "onedio_ekonomi",
    name: "Onedio Ekonomi",
    url: "https://onedio.com/Publisher/publisher-ekonomi.rss",
    icon: "https://onedio.com/favicon.ico",
    categories: ["business"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "onedio_finans",
    name: "Onedio Finans",
    url: "https://onedio.com/Publisher/publisher-finans.rss",
    icon: "https://onedio.com/favicon.ico",
    categories: ["business"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "bloomberght",
    name: "Bloomberg HT",
    url: "https://www.bloomberght.com/rss",
    icon: "https://www.bloomberght.com/favicon.ico",
    categories: ["business"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "forbes_tr",
    name: "Forbes Türkiye",
    url: "https://www.forbes.com.tr/rss",
    icon: "https://www.forbes.com.tr/favicon.ico",
    categories: ["business"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "cnbce",
    name: "CNBC-e",
    url: "https://www.cnbce.com/rss",
    icon: "https://www.cnbce.com/favicon.ico",
    categories: ["business"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "ekonomim",
    name: "Ekonomim",
    url: "https://www.ekonomim.com/rss",
    icon: "https://www.ekonomim.com/favicon.ico",
    categories: ["business"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "hurriyet_eko",
    name: "Hürriyet Ekonomi",
    url: "https://www.hurriyet.com.tr/rss/ekonomi",
    icon: "https://www.hurriyet.com.tr/favicon.ico",
    categories: ["business"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "sozcu_eko",
    name: "Sözcü Ekonomi",
    url: "https://www.sozcu.com.tr/feeds-rss-category-ekonomi",
    icon: SOZCU_FAVICON,
    categories: ["business"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "sozcu_borsa",
    name: "Sözcü Borsa",
    url: "https://www.sozcu.com.tr/feeds-rss-category-borsa",
    icon: SOZCU_FAVICON,
    categories: ["business"],
    lang: "tr",
    priority: 2,
  },

  {
    id: "doviz",
    name: "Döviz",
    url: "https://www.doviz.com/news/rss",
    icon: "https://www.doviz.com/favicon.ico",
    categories: ["business"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "investing_tr",
    name: "Investing.com Türkiye",
    url: "https://tr.investing.com/rss/news.rss",
    icon: "https://tr.investing.com/favicon.ico",
    categories: ["business"],
    lang: "tr",
    priority: 2,
  },

  // ── TEKNOLOJİ ────────────────────────────────────────────────────────────
  {
    id: "webrazzi",
    name: "Webrazzi",
    url: "https://webrazzi.com/feed",
    icon: "https://webrazzi.com/favicon.ico",
    categories: ["technology"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "shiftdelete",
    name: "ShiftDelete",
    url: "https://shiftdelete.net/feed",
    icon: "https://shiftdelete.net/favicon.ico",
    categories: ["technology"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "webtekno",
    name: "Webtekno",
    url: "https://www.webtekno.com/rss.xml",
    icon: "https://www.webtekno.com/favicon.ico",
    categories: ["technology"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "donanimhaber",
    name: "DonanımHaber",
    url: "https://www.donanimhaber.com/rss/tum/",
    icon: "https://www.donanimhaber.com/favicon.ico",
    categories: ["technology"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "onedio_teknoloji",
    name: "Onedio Teknoloji",
    url: "https://onedio.com/Publisher/publisher-teknoloji.rss",
    icon: "https://onedio.com/favicon.ico",
    categories: ["technology"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "chip",
    name: "Chip Online",
    url: "https://www.chip.com.tr/rss",
    icon: "https://www.chip.com.tr/favicon.ico",
    categories: ["technology"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "technopat",
    name: "Technopat",
    url: "https://www.technopat.net/feed/",
    icon: TECHNOPAT_ICON,
    categories: ["technology"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "log",
    name: "LOG",
    url: "https://www.log.com.tr/feed/",
    icon: "https://www.log.com.tr/favicon.ico",
    categories: ["technology"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "teknoblog",
    name: "Teknoblog",
    url: "https://www.teknoblog.com/feed/",
    icon: "https://www.teknoblog.com/favicon.ico",
    categories: ["technology"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "hwp",
    name: "Hardware Plus",
    url: "https://hwp.com.tr/feed",
    icon: "https://hwp.com.tr/favicon.ico",
    categories: ["technology"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "donanimgunlugu",
    name: "Donanım Günlüğü",
    url: "https://donanimgunlugu.com/feed",
    icon: "https://donanimgunlugu.com/favicon.ico",
    categories: ["technology"],
    lang: "tr",
    priority: 3,
  },

  // ── SPOR ────────────────────────────────────────────────────────────────
  {
    id: "fanatik",
    name: "Fanatik",
    url: "https://www.fanatik.com.tr/rss.xml",
    icon: "https://www.fanatik.com.tr/favicon.ico",
    categories: ["sports"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "onedio_spor",
    name: "Onedio Spor",
    url: "https://onedio.com/Publisher/publisher-spor.rss",
    icon: "https://onedio.com/favicon.ico",
    categories: ["sports"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "fotomac",
    name: "Fotomaç",
    url: "https://www.fotomac.com.tr/rss/anasayfa.xml",
    icon: "https://www.fotomac.com.tr/favicon.ico",
    categories: ["sports"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "euronews_spor",
    name: "Euronews Spor",
    url: "https://tr.euronews.com/rss?format=mrss&level=theme&name=sport",
    icon: "https://tr.euronews.com/favicon.ico",
    categories: ["sports"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "ntvspor",
    name: "NTV Spor",
    url: "https://www.ntvspor.net/rss/anasayfa",
    icon: "https://www.ntvspor.net/favicon.ico",
    categories: ["sports"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "ajansspor",
    name: "AjansSpor",
    url: "https://ajansspor.com/rss",
    icon: "https://ajansspor.com/favicon.ico",
    categories: ["sports"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "aspor",
    name: "A Spor",
    url: "https://www.aspor.com.tr/rss/anasayfa.xml",
    icon: "https://www.aspor.com.tr/favicon.ico",
    categories: ["sports"],
    lang: "tr",
    priority: 2,
  },

  {
    id: "sozcu_spor",
    name: "Sözcü Spor",
    url: "https://www.sozcu.com.tr/feeds-rss-category-spor",
    icon: SOZCU_FAVICON,
    categories: ["sports"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "hurriyet_spor",
    name: "Hürriyet Spor",
    url: "https://www.hurriyet.com.tr/rss/spor",
    icon: "https://www.hurriyet.com.tr/favicon.ico",
    categories: ["sports"],
    lang: "tr",
    priority: 2,
  },

  {
    id: "fotomac_slig",
    name: "Fotomaç Süper Lig",
    url: "https://www.fotomac.com.tr/rss/SuperLig.xml",
    icon: "https://www.fotomac.com.tr/favicon.ico",
    categories: ["sports"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "ntv_futbol",
    name: "NTV Spor Futbol",
    url: "https://www.ntvspor.net/rss/kategori/futbol",
    icon: "https://www.ntvspor.net/favicon.ico",
    categories: ["sports"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "kontraspor",
    name: "Kontraspor",
    url: "https://kontraspor.com/rss",
    icon: "https://kontraspor.com/favicon.ico",
    categories: ["sports"],
    lang: "tr",
    priority: 3,
  },
  // ── SAĞLIK ──────────────────────────────────────────────────────────────
  {
    id: "onedio_saglik",
    name: "Onedio Sağlık",
    url: "https://onedio.com/Publisher/publisher-saglik.rss",
    icon: "https://onedio.com/favicon.ico",
    categories: ["health"],
    lang: "tr",
    priority: 2,
  },
  
  {
    id: "saglik_haberler",
    name: "Sağlık Haberleri",
    url: "https://www.haberler.com/saglik/rss/",
    icon: "https://www.haberler.com/favicon.ico",
    categories: ["health"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "sozcu_saglik",
    name: "Sözcü Sağlık",
    url: "https://www.sozcu.com.tr/feeds-rss-category-saglik",
    icon: SOZCU_FAVICON,
    categories: ["health", "lifestyle"],
    lang: "tr",
    priority: 2,
  },

  // ── DÜNYA ────────────────────────────────────────────────────────────────
  {
    id: "aa_dunya",
    name: "AA Dünya",
    url: "https://www.aa.com.tr/tr/rss/default?cat=dunya",
    icon: "https://www.aa.com.tr/favicon.ico",
    categories: ["world"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "euronews_dunya",
    name: "Euronews Dünya",
    url: "https://tr.euronews.com/rss?format=mrss&level=theme&name=news",
    icon: "https://tr.euronews.com/favicon.ico",
    categories: ["world"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "hurriyet_dunya",
    name: "Hürriyet Dünya",
    url: "https://www.hurriyet.com.tr/rss/dunya",
    icon: "https://www.hurriyet.com.tr/favicon.ico",
    categories: ["world"],
    lang: "tr",
    priority: 2,
  },

  // ── BİLİM ────────────────────────────────────────────────────────────────
  {
    id: "evrimagaci",
    name: "Evrim Ağacı",
    url: "https://evrimagaci.org/rss.xml",
    icon: "https://evrimagaci.org/favicon.ico",
    categories: ["science"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "sarkac",
    name: "Sarkaç",
    url: "https://sarkac.org/feed/",
    icon: "https://sarkac.org/favicon.ico",
    categories: ["science"],
    lang: "tr",
    priority: 1,
  },

  {
    id: "bilimvegelecek",
    name: "Bilim ve Gelecek",
    url: "https://bilimvegelecek.com.tr/index.php/feed/",
    icon: "https://bilimvegelecek.com.tr/favicon.ico",
    categories: ["science"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "kozmikanafor",
    name: "Kozmik Anafor",
    url: "https://www.kozmikanafor.com/feed/",
    icon: "https://www.kozmikanafor.com/favicon.ico",
    categories: ["science"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "popsci_tr",
    name: "Popular Science Türkiye",
    url: "https://popsci.com.tr/feed/",
    icon: "https://popsci.com.tr/favicon.ico",
    categories: ["science"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "herkese_bilim",
    name: "Herkese Bilim Teknoloji",
    url: "https://www.herkesebilimteknoloji.com/feed",
    icon: "https://www.herkesebilimteknoloji.com/favicon.ico",
    categories: ["science"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "arkeofili",
    name: "Arkeofili",
    url: "https://arkeofili.com/feed/",
    icon: "https://arkeofili.com/favicon.ico",
    categories: ["science"],
    lang: "tr",
    priority: 3,
  },

  // ── KÜLTÜR & SANAT ────────────────────────────────────────────────────────
  {
    id: "fikirturu",
    name: "Fikir Turu",
    url: "https://fikirturu.com/feed",
    icon: "https://fikirturu.com/favicon.ico",
    categories: ["culture"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "arkitera",
    name: "Arkitera",
    url: "https://www.arkitera.com/feed/",
    icon: "https://www.arkitera.com/favicon.ico",
    categories: ["culture"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "artkolik",
    name: "Artkolik",
    url: "https://www.artkolik.net/feed",
    icon: "https://www.artkolik.net/favicon.ico",
    categories: ["culture"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "bantmag",
    name: "Bant Mag",
    url: "https://bantmag.com/feed/",
    icon: "https://bantmag.com/favicon.ico",
    categories: ["culture"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "sosyalbilimler",
    name: "Sosyal Bilimler",
    url: "https://www.sosyalbilimler.org/feed/",
    icon: "https://www.sosyalbilimler.org/favicon.ico",
    categories: ["culture"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "edebiyathaber",
    name: "Edebiyat Haber",
    url: "https://www.edebiyathaber.net/feed/",
    icon: "https://www.edebiyathaber.net/favicon.ico",
    categories: ["culture"],
    lang: "tr",
    priority: 3,
  },

  // ── SAVUNMA SANAYİ ────────────────────────────────────────────────────────
  {
    id: "defenceturk",
    name: "DefenceTurk",
    url: "https://www.defenceturk.net/feed",
    icon: "https://www.defenceturk.net/favicon.ico",
    categories: ["defense"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "savunmasanayist",
    name: "SavunmaSanayiST",
    url: "https://www.savunmasanayist.com/feed/",
    icon: "https://www.savunmasanayist.com/favicon.ico",
    categories: ["defense"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "c4defence",
    name: "C4 Defence",
    url: "https://www.c4defence.com/feed/",
    icon: "https://www.c4defence.com/favicon.ico",
    categories: ["defense"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "mavisavunma",
    name: "Mavi Savunma",
    url: "https://mavisavunma.com/feed/",
    icon: "https://mavisavunma.com/favicon.ico",
    categories: ["defense"],
    lang: "tr",
    priority: 2,
  },

  // ── ENTERTAİNMENT ────────────────────────────────────────────────────────
  {
    id: "onedio_dizifilm",
    name: "Onedio",
    url: "https://onedio.com/Publisher/publisher-dizi+%26+film.rss",
    icon: "https://onedio.com/favicon.ico",
    categories: ["entertainment"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "onedio_tv",
    name: "Onedio TV",
    url: "https://onedio.com/Publisher/publisher-tv.rss",
    icon: "https://onedio.com/favicon.ico",
    categories: ["entertainment"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "beyazperde",
    name: "Beyaz Perde",
    url: "https://www.beyazperde.com/rss/haberler.xml",
    icon: "https://www.beyazperde.com/favicon.ico",
    categories: ["entertainment"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "ign_tr",
    name: "IGN Türkiye",
    url: "https://tr.ign.com/feed.xml",
    icon: "https://tr.ign.com/favicon.ico",
    categories: ["entertainment"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "mobidictum",
    name: "Mobidictum",
    url: "https://mobidictum.com/tr/feed/",
    icon: "https://mobidictum.com/favicon.ico",
    categories: ["entertainment"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "bilimkurgukulubu",
    name: "Bilimkurgu Kulübü",
    url: "https://www.bilimkurgukulubu.com/feed/",
    icon: "https://www.bilimkurgukulubu.com/favicon.ico",
    categories: ["entertainment"],
    lang: "tr",
    priority: 2,
  },

  // ── YAŞAM / LİFESTYLE ─────────────────────────────────────────────────────
  {
    id: "onedio_yasam",
    name: "Onedio Yaşam",
    url: "https://onedio.com/Publisher/publisher-yasam.rss",
    icon: "https://onedio.com/favicon.ico",
    categories: ["lifestyle"],
    lang: "tr",
    priority: 1,
  },
  {
    id: "isindetayi_yasam",
    name: "İşin Detayı Yaşam",
    url: "https://www.isindetayi.com/rss/yasam",
    icon: "https://www.isindetayi.com/favicon.ico",
    categories: ["lifestyle"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "isindetayi_saglik",
    name: "İşin Detayı Sağlık",
    url: "https://www.isindetayi.com/rss/saglik",
    icon: "https://www.isindetayi.com/favicon.ico",
    categories: ["lifestyle", "health"],
    lang: "tr",
    priority: 2,
  },
  {
    id: "isindetayi_gastronomi",
    name: "İşin Detayı Gastronomi",
    url: "https://www.isindetayi.com/rss/gastronomi",
    icon: "https://www.isindetayi.com/favicon.ico",
    categories: ["lifestyle"],
    lang: "tr",
    priority: 2,
  },
];

// Kategoriye göre filtrele
export function getSourcesByCategory(category) {
  return RSS_SOURCES.filter((s) => s.categories.includes(category)).sort(
    (a, b) => a.priority - b.priority,
  );
}

// Tüm unique URL'leri al (tekrar etmeden)
export function getAllSources() {
  return RSS_SOURCES.sort((a, b) => a.priority - b.priority);
}
